# -*- coding: utf-8 -*-
ROWS = [
 dict(seg="Reštaurácia / penzión", firma="Motorest David", web="https://www.motorestdavid.sk", email="info@motorestdavid.sk",
      tel="+421 940 630 180", lok="Hôrka pri Poprade",
      prilez="Administrácia denného menu a oznamov s dátumom platnosti, aby staré oznamy sami mizli.",
      pitch="Ručné prepisovanie obsahu (Ponuka 3 – web/appka)", prio="Vysoká",
      pozn="Denné menu sa prepisuje na webe každý deň (31.8.2026 aj s gramážami, alergénmi a cenami). Na úvodnej stránke 31.8. stále visel oznam o zatvorených sobotách 22.08. a 29.08.2026, teda po termíne. Rezervácia ubytovania je formulár typu „ozveme sa“; na kontakte tri čísla podľa účelu. Web od webeum.eu."),
 dict(seg="Reštaurácia", firma="Slovenská reštaurácia Čadca", web="https://www.slovenskarestauraciacadca.sk", email="slovenska.restauracia2978@gmail.com",
      tel="041/433 21 32", lok="Čadca",
      prilez="Zobraziť denné menu priamo na stránke namiesto PDF na stiahnutie, čitateľne na mobile.",
      pitch="Obsah len na stiahnutie / ručné publikovanie (Ponuka 3)", prio="Stredná",
      pozn="Denné menu publikujú ako PDF – súbor 31.8.2026-1.pdf nahraný 31.08.2026 o 06:41. Web má tri stránky (Denné menu, O nás, Fotogaléria), beží na WordPress 5.8.15. Kontakt len telefón a gmail, otvorené Po–Pi 09:00–14:00."),
 dict(seg="Požičovňa", firma="Požičovňa karavanov Piešťany (Dom na kolesách)", web="https://www.pozicovna-karavanov.sk", email="info@pozicovna-karavanov.sk",
      tel="+421 908 097 896", lok="Piešťany",
      prilez="Kalendár obsadenosti pre tri karavany, kde si zákazník vyberie termín sám.",
      pitch="Chýba rezervačný základ (Ponuka 3)", prio="Vysoká",
      pozn="Tri vozidlá (Challenger C387, Ford Giottiline PS700, Rapido 8086DF) od 110 €/deň. Tlačidlá „rezervovať“ vedú na detail vozidla; jediný formulár na webe je Meno/Email/Telefón/Správa – bez dátumov a bez obsadenosti. Text sľubuje „krátky rezervačný formulár“. Silné FAQ (storno, poistenie, kľúče). WordPress."),
 dict(seg="Reštaurácia / rozvoz", firma="Pizza Delivery (WATEXI s.r.o.)", web="https://pizzadelivery.sk", email="objednavky@pizzadelivery.sk",
      tel="+421 903 666 066", lok="Bratislava",
      prilez="Objednávkový košík s adresou a časom doručenia namiesto telefonických objednávok.",
      pitch="Chýba e-shop / objednávkový systém (Ponuka 3)", prio="Vysoká",
      pozn="V aktualitách stále: „S technických príčin nie je ešte dostupný náš e-shop. Vaše objednávky príjmame aktuálne len telefonicky.“ Akcia na homepage platila 2.11.2021–31.10.2022, copyright 2021–2022. Viaceré kategórie ponuky prázdne („Pripravujeme pre Vás...“). Ceny rozvozu rozpísané po mestských častiach BA (0,60–5,50 €). Druhý mail info@pizzadelivery.sk."),
 dict(seg="Ubytovanie / chaty", firma="Chata Predná hora", web="https://www.chataprednahora.sk", email="ubytovanie@chataprednahora.sk",
      tel="0905 215 511", lok="Predná hora, Muránska planina",
      prilez="Kalendár obsadenosti pre dva objekty namiesto mailovej rezervácie s ručným výpisom údajov.",
      pitch="Chýba rezervačný základ + neudržiavaný statický web (Ponuka 3)", prio="Vysoká",
      pozn="Statický HTML web (index.html, chata1.html...). Rezervácia: hosť má poslať mail s objektom, termínom a počtom osôb. V pätičke je rok rozdielny podľa stránky – na úvode „© 2015 - 2023“, na kontaktoch „© 2015 - 2024“; pri „Posledná aktualizácia:“ chýba dátum. Dva objekty po 16 osôb, prenajímajú sa len celé. Výborný popis cesty vrátane fotky novej smerovej tabule."),
 dict(seg="Šport / voľný čas", firma="Trionfo Sport (squash – tenis – cafe)", web="https://www.trionfosport.sk", email="info@trionfosport.sk",
      tel="+421 948 101 333", lok="Prešov – Šváby",
      prilez="Sprístupniť existujúcu rezerváciu booqme priamo z webu (funkčné tlačidlo namiesto textu).",
      pitch="Rozbitý prvok na živom webe (Ponuka 3)", prio="Vysoká",
      pozn="Stránka „ONLINE REZERVÁCIA“ (?page_id=217) obsahuje len nefunkčný wp-block-embed – adresa https://booqme.sk/sk/rezervacia/squash-presov je vypísaná ako obyčajný text, nie odkaz (overené v DOM: v .entry-content nie je žiadny <a>). Na Kontakte: „REZERVÁCIE KURTOV NA TEL.č. 0948 101 333“. WordPress 5.5.20, URL bez permalinkov (?page_id=). Dva klimatizované McWil squash kurty + vonkajší tenisový kurt s osvetlením."),
 dict(seg="Kemping / ubytovanie", firma="Autocamping Podlesok s.r.o.", web="https://www.podlesok.sk", email="recepcia@podlesok.sk",
      tel="+421 53 429 91 65", lok="Hrabušice, Slovenský raj",
      prilez="Online rezervácia chatiek a elektrických prípojok pre karavany.",
      pitch="Chýba rezervačný základ (Ponuka 3)", prio="Vysoká",
      pozn="Areál 4 ha, kapacita 600 stanových miest, 32 elektrických prípojok pre karavany. V menu Ubytovanie / Služby / Okolie / Dokumenty / Kontakty – rezervácia nikde, kontakt len telefón a mail na recepciu. Na úvode živá panoráma a teplota z holidayinfo.sk. Web na CMS Galileo Corporation."),
 dict(seg="Kurzy / škola", firma="Tanečná škola Veternica", web="https://veternica.com", email="ts.veternica@gmail.com",
      tel="0907 467 421", lok="Bratislava (Iuventa, Karloveská 64)",
      prilez="Doplniť chýbajúce stránky podmienok a ochrany údajov naviazané na prihlášku pre deti.",
      pitch="Rozbité odkazy pri formulári so zberom údajov detí (Ponuka 3)", prio="Vysoká",
      pozn="Online prihláška zbiera meno, priezvisko, adresu a dátum narodenia dieťaťa, ročník, škôlku (MŠ Rača, Devín, M. Hodžu, CMŠ Bilíková) a kontaktnú osobu. V pätičke odkazy „Zmluvnými podmienkami“ a „Pravidlami ochrany osobných údajov“ vedú na href=\"#\" (overené v DOM). Nábor od septembra 2026, deti 3–15 r. + FS Vývrtka. Web na builderi (ws-block-*)."),
 dict(seg="Výroba / remeslo", firma="Minipivovar BUCHVALD s.r.o.", web="https://www.buchvald.sk", email="radofassinger@gmail.com",
      tel="+421 944 581 185", lok="Spišská Nová Ves",
      prilez="Malá appka na evidenciu sudov a zapožičaných výčapov (kto, dokedy, aká záloha).",
      pitch="Ručná agenda bez systému (Ponuka 3)", prio="Stredná",
      pozn="Detailný cenník: 50l ležiak 12° 134 €, záloha za KEG 50 €, výčap na deň 10 € / víkend 20 €, záloha 100 €, vrátenie do 10:00. Na Kontaktoch: „zapožičanie prenosného výčapu je potrebné dohodnúť vopred telefonicky“. Kontaktné maily nie sú na vlastnej doméne – novotny@bbfenergy.sk a radofassinger@gmail.com. Pätička „© 2019 BUCHVALD“. Hlavný sládek Ing. Peter Novotný."),
 dict(seg="Výroba / remeslo", firma="KRIMAX s.r.o.", web="https://krimax.sk", email="krimax@krimax.sk",
      tel="+421 908 125 048", lok="Lehota (okr. Nitra)",
      prilez="Oprava mailového odkazu v hlavičke + krátky dopytový formulár s rozmermi a fotkou.",
      pitch="Rozbitý kontakt na živom webe (Ponuka 3)", prio="Vysoká",
      pozn="V hlavičke webu je zobrazené krimax@krimax.sk, ale href odkazu je mailto:info@test.com – zvyšok šablóny (overené v DOM). V pätičke je mailto:krimax@krimax.sk správne. Žiadny kontaktný formulár na webe. WordPress 5.2.26. Kováčstvo–zámočníctvo: brány s pohonom, zábradlia, oceľové schody, prístrešky, konštrukcie; ponúkajú aj povrchové úpravy."),
 dict(seg="Reštaurácia / rozvoz", firma="Pizzeria Sicília (Galek, s.r.o.)", web="http://www.pizzeriasicilia.sk", email="info@pizzeriasicilia.sk",
      tel="+421 948 777 401", lok="Bratislava – Petržalka",
      prilez="Prechod na https a objednávka dokončiteľná na mobile na dva-tri kroky.",
      pitch="Objednávka bez zabezpečenia + statický ručne písaný web (Ponuka 3)", prio="Vysoká",
      pozn="Celý web vrátane online objednávky beží na http:// bez presmerovania na https – zákazník vidí v prehliadači „Nezabezpečené“ pri zadávaní adresy a telefónu. Meta generator: „PSPad editor“ – stránky písané ručne v textovom editore, URL s diakritikou (napr. /online-objednavka/Pizza-štangle.html). Na Kontakte päť telefónnych čísel. Prevádzkovateľ Galek, s.r.o., IČO 44068794."),
 dict(seg="Farma / e-shop", firma="Farma Východná", web="https://farmavychodna.sk", email="info@farmavychodna.sk",
      tel="0944 280 991", lok="Východná (Liptov)",
      prilez="Zviesť nákup do jednej cesty pod vlastnou doménou namiesto troch paralelných kanálov.",
      pitch="Roztrieštená cesta k objednávke (Ponuka 3)", prio="Stredná",
      pozn="E-shop v menu vedie na cudziu doménu eshop.biotatry.com. Hovädzie štvrte sa objednávajú telefonicky denne 8:00–16:00 (7,50 €/kg), menšie balenia cca 10 kg cez formulár (13 €/kg). Položka „Zážitky“ v hlavnom menu má href=\"#\". Farma 65 rokov, škótsky rohatý dobytok, syry (Bio pampúšik, Syrošík, oštiepok), prehliadky farmy a výroby čajov. Elementor 4.2.0."),
 dict(seg="Wellness / prenájom", firma="Sauna v prírode (Kalameny)", web="https://www.saunavprirode.sk", email="timbersro2025@gmail.com",
      tel="+421 908 269 663", lok="Kalameny (pri Ružomberku)",
      prilez="Jedna mailová adresa na vlastnej doméne a rýchlejšie načítanie rezervačného okna.",
      pitch="Nekonzistentný kontakt / pomalá rezervácia (Ponuka 3)", prio="Stredná",
      pozn="Mailový odkaz na webe vedie na rezervacia@saunavlese.sk – iná doména; druhý kontakt je timbersro2025@gmail.com. Rezervačný widget na /rezervacia/ sa načíta až po niekoľkých sekundách (pri prvom čítaní DOM bol na stránke len text, mapa a reCAPTCHA). Stránka „O saune“ dostupná na dvoch URL (/o-saune/ aj /o-saune-v-prirode-kalameny/). Cena 49 € / 3 h súkromne, otvorené 6:00–00:00, samoobslužná fínska sauna pri termálnom prameni."),
 dict(seg="Farma / e-shop", firma="Agrozami, spol. s r.o.", web="https://www.agrozami.sk", email="info@agrozami.sk",
      tel="0907 084 071", lok="Tvarožná (okr. Kežmarok)",
      prilez="Oprava mailových odkazov a jeden dopytový formulár namiesto piatich čísel podľa účelu.",
      pitch="Rozbitý kontakt na živom webe (Ponuka 3)", prio="Vysoká",
      pozn="Mailové odkazy na webe vedú na mailto:your@email a mailto:# – zvyšky šablóny (overené v DOM na úvode aj na Kontakte). Skutočná adresa info@agrozami.sk je na Kontakte len ako nekliknuteľný text. Päť čísel podľa účelu (mäso 2, mlieko 2, stroje/osivo 1). Homepage tlačí telefonické objednávky mäsa stredu–sobotu 8:00–16:00. WooCommerce košík funguje, WordPress 5.2.26. Doručenie do 30 km zdarma od 30 €."),
]

NO_DRAFT = [
 dict(seg="Výroba / remeslo", firma="Pálenica Kocurany", web="http://www.palenicakocurany.sk", email="",
      tel="0915 699 840", lok="Kocurany (okr. Prievidza)",
      prilez="Objednávkový kalendár pálenia; najprv však chýba mailový kontakt a https.",
      pitch="Chýba e-mail na webe (Ponuka 3 – potenciál)", prio="Stredná", status="Email chýba",
      pozn="Na celom webe nie je uvedená žiadna e-mailová adresa – len telefón 0915 699 840 („Objednávky sa prijímajú osobne alebo telefonicky“). Web beží na http:// bez https, pätička „2018 ©“. Rozpor v texte: v úvode dovoz kvasu zdarma „nad 600 litrov v okrese Prievidza“, v cenníku „nad 400 litrov“. Cena 5,60 €/l 50 %. Bez mailu neposielať."),
 dict(seg="Kurzy / rodinné centrum", firma="Rodinné centrum Rozprávka (o. z. Rodinná Rozprávka)", web="https://www.rodinnarozpravka.eu", email="",
      tel="", lok="Žilina",
      prilez="Doplniť kontaktné údaje a prihlasovanie na kurzy s evidenciou členského.",
      pitch="Chýba kontakt na webe (Ponuka 3 – potenciál)", prio="Stredná", status="Email chýba",
      pozn="Stránka Kontakt obsahuje len adresy (Majerská 1496/15 a prevádzka P. O. Hviezdoslava 9) – žiadny e-mail ani telefón, iba formulár; na celom webe nie je mailto odkaz. Týždenný rozvrh kurzov je ručne udržiavaný na úvode. Členské 9,90 € jednorazovo / 29,70 € mesačne. WordPress 7.1. Zbierka „Pomôžme presťahovať Rozprávku“. Bez mailu neposielať."),
 dict(seg="Ubytovanie / chaty", firma="Chata pod Chlebom", web="https://chatapodchlebom.sk", email="chatapodchlebom@gmail.com",
      tel="", lok="Malá Fatra, 1423 m n. m.", status="Treba research",
      prilez="Zjednotiť dve paralelné rezervačné cesty na stránke Ubytovanie.",
      pitch="Zatiaľ bez dostatočne konkrétneho nálezu", prio="Nízka",
      pozn="Overované 31.08.2026: na /ubytovanie/ bežia paralelne dva formuláre – rezervačný kalendár DOPBSP (vrátane polí na platobnú kartu) a samostatný Contact Form 7 – plus rezervácia mailom; text hovorí, že rezervácia platí až po ručnom potvrdení. Skrytý editorský nadpis „Modifikovateľný oznam...“ v HTML je pre návštevníka neviditeľný (rozmer 0x0), preto sa ako nález nepoužil. Kapacita 2× 9 + 5 lôžok + podkrovie, 29 €/os. Draft nevznikol – nález nie je dosť konkrétny."),
]
